### ISSUE TITLE
Testing fcp creation/cancel/concerns

### ISSUE THREAD

**Issue by anp** [anp/rfcbottest#1]
So, here's this thing. And we should totally reach consensus about it. Like right now.

**Comment by dikaiosune** [comment]
@rfcbot fcp close

I don't think we should do this thing.

**Comment by dikaiosune** [comment]
@rfcbot fcp close

I uh totally remember how this is supposed to work.

**Comment by dikaiosune** [comment]
@rfcbot fcp close

I don't think we should do this.

**Comment by dikaiosune** [comment]
@rfcbot fcp close

I *still* don't think we should do this.

**Comment by dikaiosune** [comment]
@rfcbot fcp merge

I changed my mind.

**Comment by dikaiosune** [comment]
@rfcbot fcp postpone

Let's do another for good measure.

**Comment by dikaiosune** [comment]
OK maybe this time I'll try writing the justification first.

@rfcbot fcp merge

And another note afterwards.

**Comment by anp** [comment]
@rfcbot fcp merge

Let's try again.

**Comment by dikaiosune** [comment]
@rfcbot concern This is a really bad idea. I think.

**Comment by dikaiosune** [comment]
@rfcbot resolve This is a really bad idea. I think.

**Comment by dikaiosune** [comment]
@rfcbot resolved This is a really bad idea. I think.

**Comment by dikaiosune** [comment]
@rfcbot resolved This is a really bad idea. I think.

**Comment by anp** [comment]
@rfcbot concern trying to get the right resolve message

**Comment by anp** [comment]
@rfcbot resolved trying to get the right resolve message

**Comment by anp** [comment]
@rfcbot concern what about dupes

**Comment by anp** [comment]
@rfcbot resolved what about dupes

**Comment by anp** [comment]
@rfcbot fcp cancel

**Comment by anp** [comment]
@rfcbot fcp close

I think there's been enough testing for now. Next up -- review requests.

**Comment by anp** [comment]
@rfcbot concern maybe not yet

**Comment by anp** [comment]
@rfcbot resolved non-existent concern
