### ISSUE TITLE
Let's do the thing again

### ISSUE THREAD

**Issue by anp** [anp/rfcbottest#2]
totally!

**Comment by dikaiosune** [comment]
I don't think so.

@rfcbot fcp close

**Comment by dikaiosune** [comment]
@rfcbot fcp close

**Comment by dikaiosune** [comment]
@rfcbot fcp merge

**Comment by dikaiosune** [comment]
@rfcbot fcp merge

**Comment by dikaiosune** [comment]
@rfcbot fcp merge

**Comment by dikaiosune** [comment]
@rfcbot fcp merge

**Comment by dikaiosune** [comment]
@rfcbot fcp merge

Again, i say!

**Comment by anp** [comment]
@rfcbot fcp merge

Lets do it

**Comment by anp** [comment]
@rfcbot concern I don't think we're ready for this yet

**Comment by anp** [comment]
@rfcbot resolved I don't think we're ready for this yet

**Comment by anp** [comment]
@rfcbot fcp cancel

**Comment by anp** [comment]
@rfcbot fcp close

I've changed my mind.

**Comment by anp** [comment]
@rfcbot concern foo

**Comment by anp** [comment]
@rfcbot resolved bar

**Comment by anp** [comment]
@rfcbot resolved foo

**Comment by dikaiosune** [comment]
@rfcbot fcp close

alright

**Comment by dikaiosune** [comment]
@fcp cancel
